import React from 'react';
import ProjectsPage from '../components/ProjectsPage';
import { CircleStackIcon } from '@heroicons/react/24/outline';
import Image from 'next/image';

const DataEngineering: React.FC = () => {
  const projects = [
    {
      title: "Weather and Financial Data Pipeline",
      description: "Developed a data pipeline and backend for a large-scale financial analysis application.\n\nThe app integrated weather data, energy prices, and site-specific data to calculate expected solar site revenues, used by the finance team to make investment decisions. Integrated financial data (Bloomberg API) with weather data (SolarGIS API) and site-specific data (Google Maps API) and processed using Apache Spark.\n\nTime series data on solar production from existing solar sites was also integrated into the tool, data was streamed into a data warehouse using Apache Kafka.",
      technologies: [
        { icon: "/images/python.svg", name: "Python", invert: false },
        { icon: "/images/postgresql.svg", name: "PostgresSQL", invert: false },
        { icon: "/images/apache_spark.svg", name: "Apache Spark", invert: false },
        { icon: "/images/apache_kafka.svg", name: "Apache Kafka", invert: true },
      ],
      githubUrl: null,
      image: {
        src: "weather_and_financial_data.jpg",
        alt: "Weather and Financial Data Pipeline Architecture"
      }
    },
    {
      title: "Ecommerce Data Warehouse + CRM",
      description: "Created a Snowflake data warehouse for an eBay seller. The client wanted both a CRM and a data warehouse to track their customers and their orders. They wanted to see the revenue generated by each customer and which were their best selling items.\n\nI used the eBay API to load data into the data warehouse and then used the data warehouse as a source for the CRM. The data warehouse served a dashboard which tracked the key metrics that the client wanted to see.\n\nI also built an ETL pipeline to allow the client to load Excel files into the data warehouse. Used dbt to help transform the data into the models used in the dashboard. Built the dashboard using React.",
      technologies: [
        { icon: "/images/python.svg", name: "Python", invert: false },
        { icon: "/images/postgresql.svg", name: "PostgresSQL", invert: false },
        { icon: "/images/dbt.svg", name: "dbt", invert: false },
        { icon: "/images/docker.svg", name: "Docker", invert: false },
        { icon: "/images/react.svg", name: "React", invert: false }
      ],
      githubUrl: null,
      image: {
        src: "ecommerce_data_warehouse.jpg",
        alt: "Ecommerce Data Warehouse + CRM"
      }
    }
  ];

  return (
    <ProjectsPage 
      title="Data Engineering"
      projects={projects}
    />
  );
};

export default DataEngineering;